#pragma once

#define WORK_IN_PROGRESS				DISABLE

#define ALLOCATOR_LESSON_ACTIVE			DISABLE
#define CAST_LESSON_ACTIVE				DISABLE
#define COMMA_OPERATOR_ACTIVE			DISABLE
#define CONSTEXPR_LESSON_ACTIVE			DISABLE
#define FACTORIAL_LESSON_ACTIVE			DISABLE
#define ITERATOR_LESSON_ACTIVE			DISABLE
#define ITERATORABLE_LESSON_ACTIVE		WORK_IN_PROGRESS
#define OSTREAM_LESSON_ACTIVE			DISABLE
#define POINTER_LESSON_ACTIVE			DISABLE
#define POW_LESSON_ACTIVE				DISABLE
#define SECRET_SANTA_ACTIVE				DISABLE
#define SINGLETON_LESSON_ACTIVE			DISABLE
#define TARTAGLIA_LESSON_ACTIVE			DISABLE
#define THREAD_LESSON_ACTIVE			DISABLE

class lesson {
public:
	static void run();
};